pretrained: True

device: "cuda"
learning_rate: 0.0002
max_epochs: 20
save_checkpoint_every: 5
early_stopping_patience: 8

#train_data: "C:/Users/Posajpa/PycharmProjects/Machine_Learning/Dataset1/Face Images/Final Training Images"
#train_data_labels: "C:/Users/Posajpa/PycharmProjects/Machine_Learning/Dataset1/Face Images/labels_train.txt"
#val_data: "C:/Users/Posajpa/PycharmProjects/Machine_Learning/Dataset1/Face Images/Final Testing Images"
#val_data_labels: "C:/Users/Posajpa/PycharmProjects/Machine_Learning/Dataset1/Face Images/labels_test.txt"
#val_split_req: False
#batch_size: 16

train_data_labels: "C:/Users/Posajpa/PycharmProjects/Machine_Learning/Dataset3/identity_CelebA_under_1000.txt"
train_data: "C:/Users/Posajpa/PycharmProjects/Machine_Learning/Dataset3/img_celeba_under_1000_cropped"
val_split_req: True
batch_size: 16

#train_data: "C:/Users/Posajpa/PycharmProjects/Machine_Learning/Dataset4/image_dataset"
#train_data_labels: "C:/Users/Posajpa/PycharmProjects/Machine_Learning/Dataset4/labels.txt"
#val_split_req: True
#batch_size: 64

query_data: "C:/Users/Posajpa/PycharmProjects/Machine_Learning/test_data/query"
gallery_data: "C:/Users/Posajpa/PycharmProjects/Machine_Learning/test_data/gallery"
