pretrained: True

device: "cuda"
learning_rate: 0.0002
max_epochs: 20
save_checkpoint_every: 5
early_stopping_patience: 8

train_data_labels: "path to identity_CelebA_under_1000.txt"
train_data: "path to img_celeba_under_1000_cropped"
val_split_req: True
batch_size: 16

query_data: "path to test_data/query"
gallery_data: "path to test_data/gallery"
